@extends('Layouts.home')
@section('title')
FAQs
@endsection
@section('content')
<main class="" style="min-height: 60vh;"><br class="fade-appear-done fade-enter-done"><br><h2 class="center">FAQs</h2><br><div class="row container "><div class="col l6 s12"><ul class="collapsible"><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>What are the fees?</div><div class="collapsible-body"><span> Every investor is to pay a 20% withdrawal fee to complete withdrawal process and each trader gets a set percentage of the profit they make.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>How does copy trading work?</div><div class="collapsible-body"><span> Here is how the copier works: You, as an investor, simply select an expert or experts that you want to copy trades from. Once you are signed up, this is the only action needed on your part.


Once you’ve taken care of the above, you are all set. There are no codes that you need to run or signals for you to manually input. Our software will handle the trade copying automatically on your behalf. We monitor your experts trading activity and as soon as there is a trade, we calculate all the necessary parameters and execute the trade.


The only thing you have to make sure of is that you have enough available base currency that your expert trades with, in your trading account. How much is enough? First, you must meet the exchanges minimum order amount (let’s say about $10 per trade to be safe). That means that if your expert executes a 5% order, you must have at least $300 in your account total value (at 100% expert allocation as an example). This also means that you need to have at least 10% or higher in available base currency to avoid missed trades.


When the expert exits a position, you too will exit it. Automatically. You can also change allocation at any time.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>Who are the trading experts?</div><div class="collapsible-body"><span> We carefully select expert applicants. We get to know them as a trader and examine their trading performance over a period of time. We also tend to look for expert who already have a following to further confirm their competence (social proof). You can also read about every expert on their individual performance pages.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>Do I Need to Install Any Trading Software?</div><div class="collapsible-body"><span> You can trade on our online platform in the web version right after you create an account. There is no need to install new software.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>What is the recommended amount to start with?</div><div class="collapsible-body"><span> We suggest to have around $3000-$5000 in your account in BTC value due to exchanges minimum order requirements and so that you can at least cover the subscription cost every month.</span></div></li></ul></div><div class="col l6 s12"><ul class="collapsible"><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>Are you mining for yourself?</div><div class="collapsible-body"><span> Besides the fact that we ourselves mine with the very same hardware that we offer to our clients, our capital is limited. We believe that Bitcoin and Altcoin mining is one of the best ways to receive Cryptocurrencies, however, we do not want to “put all our eggs in one basket”.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>What is the maintenance fee?</div><div class="collapsible-body"><span> Some of our products have a maintenance fee attached. The maintenance fee covers all costs related to mining including, inter alia:

electricity cost
cooling
maintenance work
hosting services

The fee is fixed in USD but deducted from the daily mining rewards in the natively mined coin on a daily basis.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>How does Bitcoin mining work</div><div class="collapsible-body"><span> It’s quick and very easy! As soon as we receive your payment your contract will be added to your profile, and you can immediately start mining. Depending on the blockchain algorithm you select and the associated mining service agreement you enter into, you can either mine native cryptocurrencies directly or allocate your hashpower to other cryptocurrencies (marked with AUTO), and even choose a specific allocation for them. For example: 60% LTC, 20% BTC and 20% DOGE. The first mining output is released after 48 hours, and then a daily mining output will follow.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>Where is your mining farm located?</div><div class="collapsible-body"><span> For security reasons, we do not disclose the exact location of our mining farms. As of April 2015, we are operating several mining farms that are located in Europe, America and Asia. Electricity cost and availability of cooling are important, but not the only criteria. See our Datacenters page for more information.</span></div></li><li><div class="collapsible-header" tabindex="0"><i class="material-icons notranslate">arrow_drop_down</i>Which pools are you using for mining?</div><div class="collapsible-body"><span> We do not publish a list of pools we are using. Our main criteria for a good pool are: reliability, fee structure and reject rate. Going forward we will solo-mine a few coins (and pass the fee savings to our users!).

Our internal policy is: “be a good crypto citizen”. This means, that we will at least use two different pools (in some cases we use up to four) for each coin. This is to preserve the decentralized nature of the crypto networks! If we become aware that a pool is getting close to 50% share, we will switch away from it and use a backup instead.</span></div></li></ul></div></div><br><br><br><br></main>
@endsection